### PR TITLE
Rails 6 upgrade

### PR DESCRIPTION
**Pull request by tquang1708**
[https://www.pivotaltracker.com/story/show/176342671]

### CODE REVIEW

**Comment by tquang1708** [comment]
A lot of the tests (like a good 80-90%) failed due to missing "optional: true"s so it might be a good idea to go through everything and see which ones need "optional: true"s.

**Comment by amichal** [comment]
@tquang1708 @yakloinsteak @eanders I merged pre-release since @yakloinsteak suggested it might fix the CI build errors.

**Review by eanders — DISMISSED** [review]
@tquang1708 , can you see if you can work through the boot issues if you set 
```
  config.cache_classes = true
 config.eager_load = true
```
in
`config/environments/development.rb` and then run `dcr web`?

**Comment by yakloinsteak** [comment]
@eanders A little unclear how we were green in the past, but we're green again.

**Comment by yakloinsteak** [comment]
@eanders I'm leaving this where it is for now. Last commits were to downcase filenames:

Found them with this after disabling bootsnap and spring:
```
Dir.glob('app/**/*.rb').to_a.each { |f| if f.match?(/[A-Z]/) then  puts f; require_relative f; end }
```

* not 100% sure I disabled zeitwerk correctly
* Didn't remove bootsnap quite yet as I want to see why the default is for all environments out of the box. There might be a reason for that.

**Pull request closed without merging**
