### PR TITLE
Only require EnrollmentCoC on non-WIP Enrollments

### PR DESCRIPTION
**Pull request by gigxz**
https://www.pivotaltracker.com/story/show/185995330

### CODE REVIEW

**Review by eanders — APPROVED** [review]
This seems  fine to me, but maybe better to just expose the picker if there's more than one.

**Comment by gigxz** [comment]
I guess why expose the picker here vs. on the Intake Assessment? I don't have a good sense of that. There could be any number of "required" questions that are asked on the Intake, not at time of enrollment. 
Maybe if the CoC should affect other behavior - like which services are avialable, or something like that.

Or if they go back for the assessment and don't know which CoC they were at? 🧐 I don't really know about the use case here

**Comment by eanders** [comment]
I'm good with this solution.  I guess I missed that we can enroll without having it drop you into the intake assessment.  Let's merge.

**Comment by gigxz** [comment]
Ok. Merging to unblock the current situation, maybe will follow up to add this question to the enrollment form (in addition to the intake assessment where it already exists)

**Pull request merged**
