### PR TITLE
Upgrades service_history_services partitioning.

### PR DESCRIPTION
**Pull request by yakloinsteak**
## Description

Switches `service_history_services` partitioning from inheritance to declarative. Adds an unrelated index

## Type of change
- [x] Code clean-up / housekeeping

## Checklist before requesting review
- [x] I have performed a self-review of my code
- [x] I have run the code that is being changed under ideal conditions, and it doesn't fail
- [x] My code includes comments and/or descriptive variable names to help other engineers understand the intent (or not applicable)
- [x] My code follows the style guidelines of this project (rubocop)
- [x] I have updated the documentation (or not applicable)

### CODE REVIEW

**Comment by yakloinsteak** [comment]
@eanders Can you let me know what I could run locally to start to test this? Or, I could pass off the testing to somebody else.

**Comment by eanders** [comment]
`rails grda_warehouse:daily` will cover inserting/updating the service_history_services table, but you would need some base data.

Alternatively, you could _just_ rebuild things that need processing:
```
GrdaWarehouse::Tasks::ServiceHistory::Enrollment.limit(5).to_a.map(&:invalidate_source_data!)
GrdaWarehouse::Tasks::ServiceHistory::Enrollment.batch_process_unprocessed!
```

Running something like `GrdaWarehouse::Hud::Enrollment.first.service_history_services` should give you back some services after running the daily task or the rebuild.

**Comment by yakloinsteak** [comment]
Saw your comment after I tagged you to review. I'll try what you posted.

**Comment by yakloinsteak** [comment]
I think that all worked, but I'm not sure what I'm looking for regarding failure beyond obvious table name things. I'm going to consider this ready for review.

**Review by eanders — APPROVED** [review]
Thanks @yakloinsteak !  I'll give this a go locally, then merge.  Should be wonderful!

**Pull request merged**
