### PR TITLE
Permission save in table

### PR DESCRIPTION
**Pull request by jgoley**
@eanders  here's a WIP of editing/saving role permissions within the data table. Locally I'm having an issue with the ajax request. It may be that I'm running my app locally outside of a docker container. It's currently setup to pretend like the requests are successful.

The requests fail with a 500 and the body of the response reads: 
```ActiveRecord::ConnectionNotEstablished
No connection pool with 'primary' found.
Extracted source (around line #1032):

#1030       def retrieve_connection(spec_name) #:nodoc:
#1031         pool = retrieve_connection_pool(spec_name)
*1032         raise ConnectionNotEstablished, "No connection pool with '#{spec_name}' found." unless pool
#1033         pool.connection
#1034       end
#1035 

Extracted source (around line #118):

#116 
#117     def retrieve_connection
*118       connection_handler.retrieve_connection(connection_specification_name)
#119     end
#120 
#121     # Returns +true+ if Active Record is connected.

Extracted source (around line #90):

#88     # to any of the specific Active Records.
#89     def connection
*90       retrieve_connection
#91     end
#92 
#93     attr_writer :connection_specification_name


Rails.root: /Users/jgoley/code/hmis-warehouse

Framework Trace
/Users/jgoley/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:1032:in `retrieve_connection'
```
I see this sometimes when loading pages so I suspect something is up with my environment. Or maybe something's up with the request? Any ideas for a resolution to the `No connection pool with 'primary' found.` error, generally, would be appreciated.

TODO: 
- [x] Use the _pretty_boolean_ styling for checkboxes to increase click target area, improve UX
- [x] Change UX of saving — is it appropriate for the saving UI to take up the whole width of the page since the behavior is specific to the table.
- [x] Improve saving/loading indicator
- [x] Fix issues with AJAX request
- [x] Add support for `Promise` api in legacy browsers 
- [x] refactor css out of the view
- [x] Fix filtration issue
- [ ] Fix slow requests
- [x] Test in legacy browsers
- [x] Add indication of error or failure

### CODE REVIEW

**Comment by eanders** [comment]
@jgoley, I haven't seen that issue before, but @yakloinsteak may have a thought.  It may just be the the configuration settings have changed since you last ran the app.  I'm happy to look at it with you on Monday if you have time.

**Comment by eanders** [comment]
I did some really basic testing.  

- The saving seems to work, though it's slow and throws a bunch of background 404s.  
- Filtering doesn't seem to work yet
- Searching doesn't seem to work yet
- It's probably ok that it's immediately editable since it's very clear you need to click save for it to save, but I think it also needs a cancel option in case you don't want to save your changes
- It throws up a scary warning about leaving the page even when the save was successful (losing unsaved work.) 

Nice work so far!

**Comment by jgoley** [comment]
@eanders Thanks for taking a look!

A few notes:
- I may have broken the filtration when refactoring for this work, my bad — I'll check on it. It should be working in this PR: https://github.com/greenriver/hmis-warehouse/pull/908

**Comment by jgoley** [comment]
@eanders I'm not sure what's going on with saving. I've tried chaining the requests but any amount over 1 take an oddly long time. Maybe we should handle it in one request? Or is there something server-side that could be slowing it?

**Comment by eanders** [comment]
@jgoley, this looks good to me.  I just did some minor cleanup of the edit screen.  If we can get it to pass the test suite, I think we can merge it.  I also think saving will be significantly faster in production.  It looks fine when changing just one role, and I think we're just waiting for puma to spin up another worker for the subsequent ones.

**Pull request merged**
