### PR TITLE
186685876-mci-timeout

### PR DESCRIPTION
**Pull request by ttoomey**
[//]: # 'remove this if PR is for a release-* branch'
# _Please squash merge this PR_

## Description
[186685876](https://www.pivotaltracker.com/story/show/186685876)

Bug:
While the extended timeout works for the initial token request, the default 5 sec timeout is applied to the subsequent resource request for some reason. This seems to be an issue in farday, rather than the oauth2 lib that calls it.

Solution:
It's possible to use a monkey patch to address this but I think it is better to upgrade faraday to fix the bug. This is a bit complicated because our custom fork of the hellosign-ruby-sdk gem has a dependency on faraday 2.2.x and prevents upgrading to 2.7 (current). To upgrade we need to patch our fork.

The HelloSign dependency is no longer needed but can be left as-is until we can remove the dead code. It does not need QA. 

## Type of change
[//]: # 'remove options that are not relevant'
- [x] Bug fix
- [x] Dependency update

## Checklist before requesting review
- [x] I have performed a self-review of my code
- [x] I have run the code that is being changed under ideal conditions, and it doesn't fail
- [x] My code includes comments and/or descriptive variable names to help other engineers understand the intent (or not applicable)
- [x] My code follows the style guidelines of this project (rubocop)
- [x] I have updated the documentation (or not applicable)
- [x] If it's not obvious how to test this change, I have provided testing instructions in this PR or the related issue

### CODE REVIEW

**Comment by gigxz** [comment]
Thanks for tracking this down @ttoomey!! Nice work

**Review by eanders — APPROVED** [review]
Thanks for the changes!

**Review by gigxz — APPROVED** [review]
💯

**Comment by gigxz** [comment]
The test failure is a flaky one that I have seen occasionally; unrelated

**Pull request merged**
