### PR TITLE
Remove can view all reports

### PR DESCRIPTION
**Pull request by awisema**
This needs to be deployed separately from the previous report permissions PR since it will remove the permission `can_view_all_reports` that that PR depends upon.

### CODE REVIEW

**Review by eanders — COMMENTED** [review]
We should revisit this.  We still need a "can see all reports", but it should behave differently, so maybe it should have a new name.  Specifically, it should allow someone to see all instances of assigned reports independent of the report "owner."

**Comment by eanders** [comment]
New permission `can_administer_assigned_reports` that allows a user to see and edit/delete reports run by other users for the reports they have access to see.  Assign in migration once to anyone with the "All HMIS Reports" access group.

**Comment by awisema** [comment]
PR #1260 needs to be deployed before this one, and the permission manually granted to the appropriate roles.

**Comment by eanders** [comment]
Closing as I believe we implemented this another way.

**Pull request closed without merging**
