### PR TITLE
Change Health::PatientReferral.active_within_range to fall back to pending_disenrollment_date

### PR DESCRIPTION
**Pull request by amichal**
It appears that in all places where this is called we are better off considering a pending disenrollment as likely to happen. Doing so will at least fix the claims reconciliation report.

Known existing callers outside of the report where I need this changed behaviour:
- [x] `Health::AgencyPerformance.patient_referrals`
- [x] `Health::Patient.active_between` called by `Health::MemberStatusReport#patient_enrolled_during_report?`
- [x] `Health::QualifyingActivity#occurred_during_any_enrollment?`

Thoughts @awisema ?

### CODE REVIEW

**Review by awisema — APPROVED** [review]

**Comment by eanders** [comment]
That looks reasonable to me.

**Comment by amichal** [comment]
@eanders The build breakage is unrelated to my work, a CVE on redcarpet needed. Did you want to handle that or have me pop an update in here?

**Comment by eanders** [comment]
That's been merged/fixed on production and pre-release.  Merging in.

**Comment by amichal** [comment]
@eanders  i chased prod on this for a while and then merged it myself since i never seemed to catch a time when it was current. Hope thats ok

**Pull request merged**
