### PR TITLE
Add rack attack to notify on excessive requests by source IP

### PR DESCRIPTION
**Pull request by amichal**
Adds rack attack with either a tracking event or throttle at 10 req/sec per source IP address.

In a test `ENV` we load it as a throttle and enabled with a special request param. In all other environments its simply a tracker for now (until  we see if we like the threshold)

In the event a throttle is triggered it is logged with various details and if configured with `EXCEPTION_WEBHOOK_URL` those details are posted to slack

Includes rspec coverage for this throttle.

### CODE REVIEW

**Comment by amichal** [comment]
@eanders I'm going to need some help getting my local test ENV in a place where i can test this out but the idea is there...

On deploy it should send rate limit violation reports to `ENV['EXCEPTION_WEBHOOK_URL`]`

**Comment by ttoomey** [comment]
@amichal this is still wip but is it intentional that it doesn't throttle requests yet? I don't see how it would work in the way that is implied by the test

Also, this is necessary per the installation instructions:
```
# In config/application.rb
config.middleware.use Rack::Attack
```

**Comment by ttoomey** [comment]
by, you'll get a file cache on production and a null cache on development.
I'm thinking a memory cache maybe best for rack attack, at least if you've got only one node
Rack::Attack.cache.store = ActiveSupport::Cache::MemoryStore.new

**Comment by eanders** [comment]
@amichal it looks like the rack_attack_spec.rb file is missing (empty.)  Can you check on that?

**Pull request merged**
