### PR TITLE
Census API adjustments

### PR DESCRIPTION
**Pull request by yakloinsteak**
## Description

Fixes some edge cases and issues with smaller populations in test suite for US Census numbers

Test with  `bundle exec rake us_census_api:all`

## Type of change
- [x] Bug fix

## Checklist before requesting review
- [x] I have performed a self-review of my code
- [x] I have run the code that is being changed under ideal conditions, and it doesn't fail
- [x] My code includes comments and/or descriptive variable names to help other engineers understand the intent (or not applicable)
- [x] My code follows the style guidelines of this project (rubocop)
- [x] I have updated the documentation (or not applicable)
- [x] If it's not obvious how to test this change, I have provided testing instructions in this PR or the related issue

### CODE REVIEW

**Comment by yakloinsteak** [comment]
I'll move this out of the draft state after everything passes, and I've run it locally for one state successfully.

**Comment by yakloinsteak** [comment]
@eanders Let me know how you want to proceed with testing this.

**Comment by yakloinsteak** [comment]
@eanders Should we merge this and follow up with other branches?

**Comment by eanders** [comment]
@yakloinsteak sounds good, merging.

**Pull request merged**
