### PR TITLE
Update enrollment management system test

### PR DESCRIPTION
**Pull request by gigxz**
[//]: # 'remove this if PR is for a release-* branch'
# _Please squash merge this PR_

## Description

* Update test that was failing because it didn't wait until the enrollment mutation completed before asserting. (new assertion to wait for dialog to closes fixes that).
* Debug logs when running the preview server
* Stop using xpath for hoh change (so we don't depend on order), though it still needs to be improved on the frontend side

## Type of change
- [x] Bug fix

## Checklist before requesting review
- [x] I have performed a self-review of my code
- [x] I have run the code that is being changed under ideal conditions, and it doesn't fail
- [x] My code includes comments and/or descriptive variable names to help other engineers understand the intent (or not applicable)
- [x] My code follows the style guidelines of this project (rubocop)
- [x] I have updated the documentation (or not applicable)
- [x] If it's not obvious how to test this change, I have provided testing instructions in this PR or the related issue

### CODE REVIEW

**Comment by martha** [comment]
@gigxz I should've checked this more carefully when reviewing your [prior PR](https://github.com/greenriver/hmis-warehouse/pull/4543/files#diff-65f2cd5c8a04de3b7f313e5555c9b0f40a874d6ffd7f858e0e1373b9d847f987R58), but this line in the instructions doesn't work for me locally:
```
docker ps -aqf "name=^hmis-warehouse_shell_run"
```
It works with hyphens instead of underscores:
```
docker ps -aqf "name=^hmis-warehouse-shell-run"
```

**Comment by gigxz** [comment]
@martha hmm okay, good to know. Seems like it might be machine-specific, so I will update the instructions to just say "use `docker ps` and copy the container ID of the shell container" like it was before. And I will just continue using my helper locally

**Comment by martha** [comment]
Sounds good. I think it could also be good to keep your helper in the docs and add an "if this doesn't work for you" troubleshooting clause!

**Comment by martha** [comment]
I also still see a pile of test failures when running locally with the current readme instructions, do you see those too? I'll debug a bit more to figure out what the problem is.
Edit: Oh never mind, this succeeds when I run against the correct frontend branch (125 not 124)!

**Comment by martha** [comment]
One test is still failing for me locally, intake_assessment_spec.rb:62. Is this succeeding for you?

**Comment by gigxz** [comment]
I have seen a lot of intermittent failures...so much so its rare to get a success (at least today when I'm trying..). I'm documenting them here https://github.com/open-path/Green-River/issues/6363 but haven't had time to really investigate

edit: that problem was fixed with https://github.com/greenriver/hmis-warehouse/pull/4548/commits/de85ef0ccf46c849145133257cb16c841bbfa17d, thanks to @ttoomey!

**Comment by gigxz** [comment]
This should be good to go, feel free to merge

**Review by ttoomey — APPROVED** [review]
looks great, thanks!

**Review by martha — APPROVED** [review]

**Comment by martha** [comment]
@ttoomey would you like to merge this one now as you're working on #5755?

**Pull request merged**
