### PR TITLE
Default to 99 for vsp value

### PR DESCRIPTION
**Pull request by gigxz**
[//]: # 'remove this if PR is for a release-* branch'
# _Please squash merge this PR_

## Description

Resolve 99 for vsp field when nil

https://green-river.sentry.io/issues/5090154064/?referrer=slack&notification_uuid=c84ad516-c939-49b5-8a1c-6087220b2191&environment=production&alert_rule_id=14757490&alert_type=issue

To reproduce: create an organization with nil in the victim_service_provider column. Try to view in the HMIS.

## Type of change
- [x] Bug fix

## Checklist before requesting review
- [x] I have performed a self-review of my code
- [x] I have run the code that is being changed under ideal conditions, and it doesn't fail
- [x] My code includes comments and/or descriptive variable names to help other engineers understand the intent (or not applicable)
- [x] My code follows the style guidelines of this project (rubocop)
- [x] I have updated the documentation (or not applicable)
- [x] If it's not obvious how to test this change, I have provided testing instructions in this PR or the related issue

### CODE REVIEW

**Comment by gigxz** [comment]
If you don't mind this going into 108 @eanders that would be more ideal. Interim datafix is to replace `nil=>99`, but that will be overwritten on a nightly basis while imports are still occurring.

**Review by eanders — APPROVED** [review]
108 is fine.  Thanks for checking!

**Comment by gigxz** [comment]
Whoops, let me fix up the branch then.

**Comment by gigxz** [comment]
merging https://github.com/greenriver/hmis-warehouse/pull/4155 instead

**Pull request closed without merging**
