### PR TITLE
Fix names

### PR DESCRIPTION
**Pull request by ZachCMP**
https://www.pivotaltracker.com/story/show/183049944

### CODE REVIEW

**Review by gigxz — APPROVED** [review]

**Comment by gigxz** [comment]
@ZachCMP tests are failing because you need to run `rails driver:hmis:dump_graphql_schema` to update the schema

**Comment by ZachCMP** [comment]
@gigxz Yeah, I know. I was just going to roll this into the rest of the enrollment lookup stuff if that's cool with you, and I'll do that over there if so

**Comment by gigxz** [comment]
alright! that works for me

**Comment by ZachCMP** [comment]
Closing this, as it's merged into #2388

**Pull request closed without merging**
