### PR TITLE
(179839355) Add 'latest-*' tags for ECR lifecycle

### PR DESCRIPTION
**Pull request by andyzito**
This is the same as the standard pattern, except that I included branch matching on `release-*` since the release- branches are used to deploy this application. I will note that this means we'll have unused latest- tags hanging around longer than might be desirable (that is, after we move on from, say, release-9, those latest-release-9 tags will still be retained for the full lifecycle policy max). This is probably not a major issue, but just wanted to call it out.

### CODE REVIEW

**Comment by eanders** [comment]
@andyzito, which pre-cache image will it use if we're deploying a non-release branch?  (It doesn't happen too often to production, it is relatively common for testing features on staging.)

**Comment by andyzito** [comment]
@eanders This is unrelated to the pre-cache tagging stuff we were talking about. This PR does not alter the pre-cache tagging at all.

If you're deploying from non-release branches then we'll need to support those with the latest- tags as well. Are those branches tied together by a naming convention of any kind, and/or would you be willing to accept the restriction of using the `deploy-*` prefix on any branches you want to deploy?

**Comment by eanders** [comment]
At the moment there isn't any official structure on the naming convention.  I guess we should chat about what this is doing.  Maybe nothing needs to change, or maybe we can just always deploy a `release` branch.

**Comment by andyzito** [comment]
Elliot and I discussed and determined that the best way forward is to have all the `release-*` branches share a single tag (eg, `latest-release--base`). Given the way release branches are used in this project (ie, one at a time), we think this is both safe from the perspective of lifecycling, and also prevents a bunch of `latest-release-1`, `latest-release-2`, etc tags from building up in the ECR repo.

**Review by eanders — APPROVED** [review]
Pending a review by @yakloinsteak , this looks good to me.

**Review by yakloinsteak — CHANGES_REQUESTED** [review]
I looked at CAS first:
https://github.com/greenriver/boston-cas/pull/512
and the comments are the same.

**Comment by andyzito** [comment]
@yakloinsteak This is ready for another round of review. I've added functionality in the deploy scripts as discussed. Here is what we got in the ECR repo after a test deployment (the `latest--test` tag is from an earlier manual test and may be disregarded):
image

I didn't engineer around the possibility of local builds, assuming that those are not common (that is, we pull and push the image manifest without regard for whether the image has been pulled locally). Note that pushing and pulling the manifest takes a matter of seconds.

**Review by yakloinsteak — APPROVED** [review]
This makes me happy.

**Comment by yakloinsteak** [comment]
@andyzito or @eanders Whoever sees this green first can merge it in.

**Comment by eanders** [comment]
@andyzito, this is throwing the following when attempting to re-deploy the same branch to a different installation:
```
	16: from bin/deploy:8:in `<main>'
	15: from bin/deploy:8:in `each'
	14: from bin/deploy:10:in `block in <main>'
	13: from /vagrant/hmis-warehouse/config/deploy/docker/lib/deployer.rb:83:in `run!'
	12: from /vagrant/hmis-warehouse/config/deploy/docker/lib/deployer.rb:123:in `_initial_steps'
	11: from /vagrant/hmis-warehouse/config/deploy/docker/lib/deployer.rb:176:in `_build_and_push_all!'
	10: from /vagrant/hmis-warehouse/config/deploy/docker/lib/deployer.rb:216:in `_build_and_push_image'
	 9: from /vagrant/hmis-warehouse/config/deploy/docker/lib/deployer.rb:237:in `_add_latest_tag!'
	 8: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/aws-sdk-ecr-1.44.0/lib/aws-sdk-ecr/client.rb:1828:in `put_image'
	 7: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/aws-sdk-core-3.119.1/lib/seahorse/client/request.rb:72:in `send_request'
	 6: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/aws-sdk-core-3.119.1/lib/seahorse/client/plugins/response_target.rb:24:in `call'
	 5: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/aws-sdk-core-3.119.1/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
	 4: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/aws-sdk-core-3.119.1/lib/seahorse/client/plugins/request_callback.rb:71:in `call'
	 3: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/aws-sdk-core-3.119.1/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
	 2: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/aws-sdk-core-3.119.1/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
	 1: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/aws-sdk-core-3.119.1/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:22:in `call'
/home/vagrant/.rvm/gems/ruby-2.7.4/gems/aws-sdk-core-3.119.1/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call': Image with digest 'sha256:<hash>' and tag 'latest-three-warehouse-production-ecs--base' already exists in the repository with name 'open-path-warehouse' in registry with id '153758321681' (Aws::ECR::Errors::ImageAlreadyExistsException)
```

**Comment by andyzito** [comment]
@eanders Sorry about that, I should have thought to account for the case of an existing tag on the image. I've made a new PR for that: #1908

**Pull request merged**
