### PR TITLE
report duplicate custom assessments and custom services

### PR DESCRIPTION
**Pull request by ttoomey**
[//]: # 'remove this if PR is for a release-* branch'
# _Please squash merge this PR_

## Description

methods to detect and report "true" duplicate assessments and services. To be duplicates, the records must share the same attributes and cdes

## Type of change
[//]: # 'remove options that are not relevant'
- [x] Utility / Helper

## Checklist before requesting review
- [x] I have performed a self-review of my code
- [x] I have run the code that is being changed under ideal conditions, and it doesn't fail
- [x] My code includes comments and/or descriptive variable names to help other engineers understand the intent (or not applicable)
- [x] My code follows the style guidelines of this project (rubocop)
- [x] I have updated the documentation (or not applicable)
- [x] If it's not obvious how to test this change, I have provided testing instructions in this PR or the related issue

### CODE REVIEW

**Review by gigxz — APPROVED** [review]
awesome, thanks!

**Comment by ttoomey** [comment]
@gigxz just to confirm, should this merge into release-110 or 111? Thanks!

**Comment by gigxz** [comment]
110 would be ideal so we can run it sooner. @eanders that ok>?

**Comment by eanders** [comment]
Fine by me.

**Pull request merged**
