### PR TITLE
Remove water from geography shapes

### PR DESCRIPTION
**Pull request by yakloinsteak**
Removes water the easy way since tracts and block groups have an attribute that lets you know if it's all water

### CODE REVIEW

**Comment by yakloinsteak** [comment]
@eanders I'm testing my code right now even though I have a water-less shape file for one state. I'll ping you when this is ready to hand off.

**Comment by yakloinsteak** [comment]
@eanders What release branch should I rebase this on? Release 28?

**Comment by yakloinsteak** [comment]
@eanders This is the 4 hour version, but there might be some shapes going into the water if there are block groups that extend into the water a lot. If this doesn't cut it, we can switch from using "land" block groups to adding a new shape table that holds water shapes. This work won't be wasted as it will be the same general idea.

Let me know if you want to discuss, but you run the `grda_warehouse:remove_water_from_shapes` rake task.

I've only tested this locally, and I can show you the results if you want to see them in qgis.

**Comment by yakloinsteak** [comment]
rebasing and calling it a day on this.

**Comment by eanders** [comment]
Thanks!  I'll take a look, maybe we can do a quick call tomorrow or Wednesday for a demo/setup production.

**Review by eanders — APPROVED** [review]
Looks good to me.  I suggest we deploy tomorrow and test on staging.

**Pull request merged**
