### PR TITLE
Filter parameters everywhere

### PR DESCRIPTION
**Pull request by eanders**

### CODE REVIEW

**Review by yakloinsteak — APPROVED** [review]
I wonder if we want to grab the standard set of scrubbers, and then do this:

```
scrubber = lambda do |msg|
  msg.gsub(/custom_regexp/, "[FILTERED]".freeze)
end

Logstop.guard(logger, scrubber: scrubber)
```
which I was thinking about because of the SSNs without dashes. How does this even work with names? Sounds impossible.

**Comment by eanders** [comment]
I was thinking the same, basically you'd do `/(key:) "(.+?)"/`.  Then you'd have a set of keys to match against.

**Comment by yakloinsteak** [comment]
That makes sense, but I was thinking about SQL fragments like `insert into persons (ssn) values ('123-12-1234')` where you have to detect the value without a label.

**Comment by eanders** [comment]
Definitely a problem I'm not sure how to solve.

**Pull request merged**
