### PR TITLE
Ui updates clients

### PR DESCRIPTION
**Pull request by jgoley**
Takes care of updates listed in this PT Chore: https://www.pivotaltracker.com/story/show/157632261
And attempts to visually distinguish call-to-action UI elements from static tags and the like.
screen shot 2018-05-17 at 4 04 13 pm
screen shot 2018-05-17 at 4 04 30 pm
screen shot 2018-05-17 at 5 18 26 pm
screen shot 2018-05-17 at 4 05 36 pm
screen shot 2018-05-17 at 4 05 17 pm
screen shot 2018-05-17 at 4 04 45 pm

### CODE REVIEW

**Comment by eanders** [comment]
@jgoley This is looking pretty good.  A few comments attached.  Also, can we go ahead and put the menu updates into this PR too?
screen shot 2018-05-19 at 3 15 33 pm
screen shot 2018-05-19 at 3 15 48 pm
screen shot 2018-05-19 at 3 17 37 pm
screen shot 2018-05-19 at 3 21 25 pm

**Comment by jgoley** [comment]
@eanders Thanks for taking a look. I'll take care of those fixes/updates ASAP.

**Comment by eanders** [comment]
@jgoley Are these changes ready?  I'd love to get the menu fix up sooner rather than later since we're starting to run into issues with the height of it.

**Comment by jgoley** [comment]
@eanders Sorry for the delay with this. I just finished taking care of all but the CAS readiness issue.
I've redesigned the layout of the client summary area. Here's the first draft:
screen shot 2018-05-23 at 6 14 41 pm
I'll should be able to finish up the menu updates tomorrow morning.

**Comment by eanders** [comment]
Thanks @jgoley!  I'll take a look tomorrow.  As long as it fails gracefully when some of the items aren't available, that looks really nice.  

Of specific note, most people don't have photos, Chronic Status, Consent forms, VI-SPDAT Scores, Cohorts, or Housing Matches.  Confusing and complicated, but that's how the data ends up coming through.

**Pull request merged**
