### PR TITLE
Release 90

### PR DESCRIPTION
**Pull request by eanders**
## Description

Next release branch

### CODE REVIEW

**Comment by pocketfishy** [comment]
Hi @eanders, glad to see the APR and CAPER included in this PR. Do you have a sense yet when this will be merged into the stable branch?

**Comment by eanders** [comment]
@pocketfishy thanks for asking!  Yes, the APR, CAPER, and CE-APR are all included here, as is the LSA (though it requires additional infrastructure setup on AWS to function.)  This will be merged later this week, but feel free to run `release-90` on your production instance if you'd like.
Also, open an issue if you need instructions on upgrading the existing data from FY2022 -> FY2024.  There's a script to do it, or you can simply reload your entire data set via an HMIS CSV upload.

**Comment by pocketfishy** [comment]
@eanders Amazing! Thanks for letting me know, and thanks for all your hard work on this! I think I will grab the release-90 branch for now

**Comment by pocketfishy** [comment]
Hi @eanders unfortunately I have not been able to get either release-90 or release-91 working. Both give me a `ActiveRecord::PendingMigrationError`. I've spent the last couple days trying to resolve this on my end but have not been successful. Do you have an idea when the stable branch will be updated to include the 2024 APR report? We're only a few weeks away from the report deadline, and we are concerned about getting it in one time. Thank you

**Comment by eanders** [comment]
So having that code merged into `stable` won't actually solve the problem.  We'll need to update some code before that would run smoothly, merging into `stable` will just push the bootstrapping issue onto that branch.

**Comment by pocketfishy** [comment]
Do you have a sense of when that would be? I reloaded a sql dump of my existing database and I'm still running into this migration issue, even when not using bin/setup. That was why I dropped the database originally, to hopefully avoid the migration issue.

**Pull request merged**
