### PR TITLE
Upgrade bootstrap v4.3

### PR DESCRIPTION
**Pull request by jgoley**
### Upgrades bootstrap to 4.3
I've reviewed most pages...I think. There are probably some outstanding issues because a) there are undoubtedly nooks and crannies I overlooked and b) sometimes it's hard to tell if a small UI thing that's not ideal in my mind was because of the bootstrap upgrade (fixing all of these could take a while) so I mostly fixed the glaring bugs. I suppose we can give it another pass in the future—I'd like to try to consolidate areas into components to ensure consistency and making re-use more straightforward (both within each app and between the Warehouse and CAS).

A few notable changes:
- I upgraded simple form so that we can use the bootstrap 4 wrappers.
  Now the forms have validity states which probably isn't ideal? We may need to set the no-validate html attr?
- I restructured the scss files to better take advantage of Rails asset management. Now if a change is made in a file other than those in `settings`, `tools`, `vendor`, the compile time should be much shorter than in the past. (when a change is made to the aforementioned, the styles are all recompiled or at least the partials that depend on the changed file, but if a change is made to a single partial, only that file will be compiled)
  **Important note about this change**: Now we need to import the `helpers` file (`app/assets/stylesheets/application/helpers.scss`) into partials if access to settings/mixins/fns is required.

In writing this I realized we need to either import the datepicker styles or add them manually:

- [x] Update Date picker styles

### CODE REVIEW

**Comment by eanders** [comment]
Some notes (WIP, I'll update as I continue to review):
https://boston-hmis.dev/censuses
- [ ] The charts seem to be behaving oddly with extra black bits.
- [ ] The tooltips on charts (at least the nightly census charts) are also broken
- [ ] Date pickers (as mentioned above) are not coming through with styles
- [ ] Date picker icon is incorrect (I think we were missing some icon set previously, might be related.)
Screen Shot 2019-03-23 at 1 45 07 PM
- [ ] Breadcrumbs don't appear where they used to, they are pushed down, they should be snugged up about 1 line height from the top.
- [ ] Bootstrap tabs appear to have lost their styles
- [ ] The colored label/tags seem to have stacked instead of moving side-by-side
Here's a comparison of new and old
Screen Shot 2019-03-23 at 1 53 31 PM
- [ ] Select 2 has a regression of a nasty bug where, at least on Safari, it jumps to the bottom of the page when clicked.
- [ ] Not sure what's going on on the CAS Readiness page, pre-checked checkboxes have green labels, the standard selects have green checkboxes inside....
Screen Shot 2019-03-23 at 1 56 02 PM
- [ ] We lost some padding in bootstrap drop-downs (at least this one.)
Screen Shot 2019-03-23 at 1 56 57 PM
- [ ] VI-SPDAT "Upload Signed Consent Form" button needs an additional class I think.
Screen Shot 2019-03-23 at 1 58 27 PM
- [ ] Additional, probably related inputs with random green check-marks
Screen Shot 2019-03-23 at 1 58 57 PM
- [ ] Date pickers seem less connected to their buttons than before. 
Screen Shot 2019-03-23 at 1 59 53 PM
- [ ] The tabs on the file page seem happy, except, the first one always thinks it's active...
Screen Shot 2019-03-23 at 2 02 15 PM
- [ ] We lost some pill/tag/parameter things (correct on right)
Screen Shot 2019-03-23 at 2 04 30 PM
- [ ] `table.table-condensed` seems to have grown much less condensed... can we add that back in?  We use it a bunch in reporting.
- [ ]  `.pull-right` I think used to provide `text-align: right` or something similar.
Screen Shot 2019-03-23 at 2 09 16 PM
- [ ] this is another example of pull-right.  It's probably not the right way to do it, but since we've used it a bunch, I'd rather just continue supporting it for now.
Screen Shot 2019-03-23 at 2 13 30 PM

**Comment by jgoley** [comment]
- [ ] Dropdowns require two clicks

**Comment by jgoley** [comment]
@eanders Do you have an example of the `Odd lines in tables in cards, maybe?`?

**Comment by eanders** [comment]
Hmm, no.  Let's ignore that one for now.  If it pops up again we can revisit.  I can't currently find any examples.

**Comment by jgoley** [comment]
I think I found one:
Screen Shot 2019-05-09 at 3 10 56 PM

**Comment by eanders** [comment]
That was it!

**Comment by jgoley** [comment]
I suspect that's also the instance of the previous, next buttons not being style correctly. Do you recall if there were other instances?

**Comment by eanders** [comment]
In some situations they would appear on the tab directly to the left "Dashboard"

**Comment by eanders** [comment]
It looks like all of those checkboxes with no screenshot are encompassed in the screenshot below them.

**Comment by jgoley** [comment]
Oh, i see. Thanks!

**Comment by jgoley** [comment]
@eanders I think I've fixed all the listed issues!
I made some changes to the collapsible panel — created a common partial. There were a few instances that I had trouble finding in the app. Here's an example: https://github.com/greenriver/hmis-warehouse/blob/upgrade-bootstrap-v4.3/app/views/window/health/health/goal/clinicals/_clinical.haml

**Comment by eanders** [comment]
Excellent!  That particular view is only for pilot patients.  I don't think it is visible any more.  I'll see if I can force it, but should be fine.

**Comment by eanders** [comment]
@jgoley Let's go over these on a call.  Here's the next batch.

- [ ]  Can we make it so that clicking a Bootstrap Tab doesn't scroll the page? (See Client files list)
- [ ] Visiting the base files page: https://boston-hmis.dev/clients/2110/files used to load and show the consent forms by default.  They are no longer visible until you click away and back.
- [ ] Once on the files page, after clicking a tab, none of the top level tabs work.  (You can click them, but they don't take you anywhere.)
Screen Shot 2019-05-13 at 8 31 27 AM

- [ ] Select 2 Multiple is visually weird on CAS readiness page
Screen Shot 2019-05-13 at 8 23 03 AM

- [ ] Youth intake needs some padding.
Screen Shot 2019-05-13 at 8 26 06 AM

- [ ] Search results when merging a client aren't showing the client names.
Screen Shot 2019-05-13 at 8 33 37 AM

- [ ] Number inputs aren't wide enough.
Screen Shot 2019-05-13 at 8 38 13 AM

- [ ] We lost the `.mt-no-label` class.  Previously this allowed us to align buttons with inputs that had labels.  We can swap in another class, and this may only be on recently changed pages....
Screen Shot 2019-05-13 at 8 40 04 AM

- [ ] We recently added some additional filter options to various reports.  I'll need a tutorial on how best to integrate those.
Screen Shot 2019-05-13 at 8 42 28 AM

- [ ] Select2 missing place-holder text
Screen Shot 2019-05-13 at 8 48 08 AM

- [ ] Any chance we can make select2 responsive to page size changes?

- [ ] Chronic report, accordion won't expand
Screen Shot 2019-05-13 at 8 51 49 AM

- [ ] Form labels are too light.  (I think they were too dark before?)
Screen Shot 2019-05-13 at 8 53 33 AM

- [ ] Initiative reports tabs are still broken (allowing you to have 2 selected) -- same issue with claim generation https://boston-hmis.dev/warehouse_reports/health/claims
Screen Shot 2019-05-13 at 8 55 22 AM

- [ ] Decision Efficiency report is completely broken. 
Screen Shot 2019-05-13 at 9 10 33 AM

- [ ] Pages with multiple accordions jump to the top open accordion when multiple are open.
Screen Shot 2019-05-13 at 9 26 23 AM

- [ ] Re-rank on cohort is gray.  It shouldn't be.
Screen Shot 2019-05-13 at 9 32 06 AM

- [ ] Code merge issues with https://boston-hmis.dev/cohorts/13/cohort_clients/new
Screen Shot 2019-05-13 at 9 33 23 AM

- [ ] Saving indicator on cohorts isn't showing. (I had trouble getting a screenshot, but changing data should make the little green box appear near the breadcrumbs)
Screen Shot 2019-05-13 at 9 34 54 AM

- [ ] The JavaScript functionality of assigning patient referrals seems to work, but all visual indication has been removed.
Screen Shot 2019-05-13 at 9 43 37 AM

**Comment by jgoley** [comment]
There are a few pages I'm having trouble accessing and testing. I made fixes blind and hopefully the work. Pages are: 
- Initiative report (the report I have has never completed)
- Youth Intakes (for some reason I don't have permission to access the page)

I also think I've fixed _Form labels are too light. (I think they were too dark before?)_ while preserving the weight of checkboxes but there may be outlier instances that I missed.

**Comment by eanders** [comment]
@jgoley this looks awesome!  Thanks.  I'm not finding any show-stoppers.

**Pull request merged**
