### PR TITLE
Rack Attack Sentry Throttling

### PR DESCRIPTION
**Pull request by yakloinsteak**
## Description
Rack attack throttled requests are by their nature excessive, so don't pass that along to Sentry.

## Type of change
Bugfix

## Checklist before requesting review
- [x] I have performed a self-review of my code
- [x] I have run the code that is being changed under ideal conditions, and it doesn't fail
- [x] If adding a new endpoint / exposing data in a new way, I have:
  - [x] ensured the API can't leak data from other data sources
  - [x] ensured this does not introduce N+1s
  - [x] ensured permissions and visibility checks are performed in the right places
- [x] I have updated the documentation (or not applicable)
- [ ] I have added spec tests (or not applicable)
- [x] I have provided testing instructions in this PR or the related issue (or not applicable)

### CODE REVIEW

**Comment by yakloinsteak** [comment]
@eanders I tested this locally with siege and a number of hacks and it seems to work as I expected. Let me know if you want me to add formal testing to this PR.

**Review by eanders — APPROVED** [review]
Thanks @yakloinsteak, I think this looks good as is.  Let's retarget to 143 (or 144) (I'm happy to do that before merge.)  Anything else you need from me? 
We always appreciate automated tests, but if that's a huge lift, given your local testing and that we'll run it through staging sites first, it's probably fine.

**Comment by yakloinsteak** [comment]
I can retarget and look at what we already have for testing rack-attack to add to that.

**Review by eanders — APPROVED** [review]

**Comment by yakloinsteak** [comment]
Made it a little clearer and linted it. I think this is ready now.

**Pull request merged**
