### PR TITLE
Stories/uploads trigger cas flags 152286568

### PR DESCRIPTION
**Pull request by eanders**
Completes: https://www.pivotaltracker.com/story/show/152286568

### CODE REVIEW

**Comment by peterclark** [comment]
getting this error...
screen shot 2017-10-25 at 10 07 24 pm

**Comment by eanders** [comment]
Right, you have to go to admin/site configs and then click save.  They don't get loaded into memcached until that happens.  Maybe I need to add whatever that does into a migration...

**Comment by peterclark** [comment]
oh, that’s the error i get when i go to admin -> site configs.

**Comment by eanders** [comment]
Ah, did you run `bin/rake warehouse:db:migrate` ?

**Comment by peterclark** [comment]
that did it, sorry, not the first time i’ve forgotten about the warehouse migrations.

**Pull request merged**
