### PR TITLE
adds dependent destruction for some client associations

### PR DESCRIPTION
**Pull request by yakloinsteak**
https://www.pivotaltracker.com/n/projects/2591838/stories/185905151

### CODE REVIEW

**Review by eanders — APPROVED** [review]
Looks good to me.

**Comment by yakloinsteak** [comment]
@gigxz I wasn't quite sure if I was supposed to add the dependent destroy statements, but I think that's what was desired.

**Review by gigxz — APPROVED** [review]
lgtm!

**Comment by yakloinsteak** [comment]
I'm a little confused about the cancelled action run, and the rubocop issues aren't mine I don't think.

**Pull request merged**
