### PR TITLE
Display contact info from HMIS

### PR DESCRIPTION
**Pull request by gigxz**
[//]: # 'remove this if PR is for a release-* branch'
# _Please squash merge this PR_

## Description

Update methods on Warehouse Client model to pull contact information from HMIS. This will only show the most recent value per type.

This makes them show up on the Client Dashboard, and I am pretty sure it will make them show up in CAS, too, but I haven't tested that.

## Type of change
- [x] New feature (adds functionality)

## Checklist before requesting review
- [x] I have performed a self-review of my code
- [x] I have run the code that is being changed under ideal conditions, and it doesn't fail
- [x] My code includes comments and/or descriptive variable names to help other engineers understand the intent (or not applicable)
- [x] My code follows the style guidelines of this project (rubocop)
- [x] I have updated the documentation (or not applicable)
- [x] If it's not obvious how to test this change, I have provided testing instructions in this PR or the related issue

### CODE REVIEW

**Comment by gigxz** [comment]
A future improvement would be to include all values, not just the most recently updated per category, but that is a bigger change.

**Review by eanders — APPROVED** [review]
@gigxz this looks good for client contacts, but I don't think it solves the "default shlelter agency contacts".
https://github.com/greenriver/hmis-warehouse/blob/e8f882c80e860b837b3acb99e7194d6ebdbcf53a/app/models/concerns/cas_client_data.rb#L302

Do we collect an email address on the CustomAssessments?  I'm unclear if this was pulling the email from the person who submitted the assessment previously, or if that was something that was asked on the assessment.  

I wonder if we can look at the most recent CE Assessment and pull the `user.email` off that, unless we ask for a specific case manager/agency email.  It doesn't appear that the HAT has a question for staff email, so I'm going to suggest we just update this method to look for the latest CE Assessment and grab the email of the assessor.  Does that make sense?

**Comment by gigxz** [comment]
Opened https://www.pivotaltracker.com/story/show/187379214

**Review by eanders — APPROVED** [review]
Looks good to me.  Thanks!

**Pull request merged**
