### PR TITLE
aws_s3_fix_delete_method

### PR DESCRIPTION
**Pull request by ttoomey**
[//]: # 'remove this if PR is for a release-* branch'
# _Please squash merge this PR_

## Description
bugfix for delete method used by external form submission processing, add test

* fix bug in aws_s3.delete used in external form submissions
* add quick tests for the aws_s3 class
* small cleanups to external form test
* add content type to form html (fix modal close button render)

## Type of change
[//]: # 'remove options that are not relevant'
- [x] Bug fix

## Checklist before requesting review
- [x] I have performed a self-review of my code
- [x] I have run the code that is being changed under ideal conditions, and it doesn't fail
- [x] My code includes comments and/or descriptive variable names to help other engineers understand the intent (or not applicable)
- [x] My code follows the style guidelines of this project (rubocop)
- [x] I have updated the documentation (or not applicable)
- [x] If it's not obvious how to test this change, I have provided testing instructions in this PR or the related issue

### CODE REVIEW

**Review by gigxz — APPROVED** [review]
looks good to me! thanks for adding tests.

**Comment by ttoomey** [comment]
thanks @gigxz - should I merge this into release-111?

**Comment by gigxz** [comment]
Yes please @ttoomey .
For context @eanders this is a patch for the Public Forms tool which deletes submissions from S3 once they have been downloaded.

**Comment by gigxz** [comment]
Test failure was an unrelated flaky text, https://github.com/greenriver/hmis-warehouse/actions/runs/8670175575/job/23777851375 I can fix that separately

**Pull request merged**
