### PR TITLE
6566 system test ref fix

### PR DESCRIPTION
**Pull request by ttoomey**
[//]: # 'remove this if PR is for a release-* branch'
# _Please squash merge this PR_

## Description
[GH issue](https://github.com/open-path/Green-River/issues/6566)

* Only run system tests on PR so we get the correct FE release branch name from base_ref

## Type of change
[//]: # 'remove options that are not relevant'
- [x] Bug fix

## Checklist before requesting review
- [x] I have performed a self-review of my code
- [x] I have run the code that is being changed under ideal conditions, and it doesn't fail
- [x] My code includes comments and/or descriptive variable names to help other engineers understand the intent (or not applicable)
- [x] My code follows the style guidelines of this project (rubocop)
- [x] I have updated the documentation (or not applicable)
- [x] If it's not obvious how to test this change, I have provided testing instructions in this PR or the related issue

### CODE REVIEW

**Review by eanders — APPROVED** [review]
Well that's overly complicated!  (Not that we have any control over that.)  Thanks for figuring it out.

One thought, could we just make the base branch itself if it can'f find one?  Would that clear it up at all?

**Comment by ttoomey** [comment]
> Well that's overly complicated! (Not that we have any control over that.) Thanks for figuring it out.

Yeah, the alternative is to create another workflow file but copying all the boilerplate feels bad so I figured this was better (marginally). 

> One thought, could we just make the base branch itself if it can'f find one? Would that clear it up at all?

Not sure I follow. The issue is that we need to find the right release branch on the front-end repo. So if I open a new PR, issueX, against release-100 on the warehouse, we want to run the system tests against the first branch we find on the FE repo in the set [issueX, release-100, stable]. Gig found that we can't determine this release branch (r100) unless the current action is 'pull-request' so right now our system tests are defaulting to the stable FE branch

**Comment by eanders** [comment]
Thanks for the explanation, I was forgetting it was looking in the FE repo.

**Comment by eanders** [comment]
We'll need to update the branch settings with the new matrix info before the checks will align.
Screenshot 2024-08-23 at 1 18 53 PM

**Comment by ttoomey** [comment]
> We'll need to update the branch settings with the new matrix info before the checks will align.

oh good point, that's awkward that we have to enumerate all elements of the matrix but I guess there's no way around it

**Review by gigxz — APPROVED** [review]

**Pull request merged**
