### PR TITLE
Makes CI build more modular

### PR DESCRIPTION
**Pull request by yakloinsteak**

### CODE REVIEW

**Comment by yakloinsteak** [comment]
@eanders Can you look at the failures and let me know if you think they're related to my CI changes? I think the tests don't like initializing the database in our "standard" way. I see data source ID locked to 1 in one file, which seems related.

**Comment by eanders** [comment]
Yes, I'm guessing the sequences aren't getting added.  I had that trouble when moving the QA db recently.

**Comment by eanders** [comment]
Maybe we should try schema load again?  Also, it looks like you renamed the job, which we probably don't want to do unless we also go rename it in the GitHub settings.

**Comment by yakloinsteak** [comment]
@eanders This is ready to merge (or reject if you don't want to mess with it). I like it because I think it makes us closer to what we deploy. We can get even closer in the future.

**Comment by eanders** [comment]
Looks great!  I'll let the tests run once more and then merge.

**Pull request merged**
