### PR TITLE
Core Demographics and Demographic Summary reports get new race/ethnicity tables

### PR DESCRIPTION
**Pull request by eanders**
[//]: # 'remove this if PR is for a release-* branch'
# _Please squash merge this PR_

## Description

This updates the Core Demographics and Demographic Summary reports to include the new race and ethnicity tables.

## Type of change
[//]: # 'remove options that are not relevant'
- [x] New feature (adds functionality)

## Checklist before requesting review
- [x] I have performed a self-review of my code
- [x] I have run the code that is being changed under ideal conditions, and it doesn't fail
- [x] My code includes comments and/or descriptive variable names to help other engineers understand the intent (or not applicable)
- [x] My code follows the style guidelines of this project (rubocop)
- [x] I have updated the documentation (or not applicable)
- [x] If it's not obvious how to test this change, I have provided testing instructions in this PR or the related issue

### CODE REVIEW

**Review by dtgreiner — APPROVED** [review]

**Comment by ahogg77** [comment]
Most of the numbers are close but big difference in Multi Racial between Core Demo and Superset
image
image

**Comment by ahogg77** [comment]
I ran the numbers for Dec 1-Dec 31 2023 and for NBN only require services

**Comment by eanders** [comment]
Thanks @ahogg77.  I can take a look, I wonder if one of them isn't treating Hispanic/Latin@ quite right.  Can you drop links to both of those here?

**Comment by ahogg77** [comment]
https://qa-warehouse.openpath.host/core_demographics_report/warehouse_reports/demographic_summary?breakdown=none&display_project_type_ctl=custom&filters%5Bproject_type_codes%5D%5B%5D=&filters%5Bproject_type_codes%5D%5B%5D=es_nbn&filters%5Bcoordinated_assessment_living_situation_homeless%5D=0&filters%5Bce_cls_as_homeless%5D=0&filters%5Binactivity_days%5D=730&filters%5Brequire_service_during_range%5D=0&filters%5Brequire_service_during_range%5D=1&filters%5Bactive_roi%5D=0&filters%5Bstart%5D=Dec+1%2C+2023&filters%5Bend%5D=Dec+31%2C+2023&filters%5Bcomparison_pattern%5D=no_comparison_period&filters%5Bmask_small_populations%5D=0&filters%5Bcoc_codes%5D%5B%5D=&filters%5Bfunder_ids%5D%5B%5D=&filters%5Bdata_source_ids%5D%5B%5D=&filters%5Borganization_ids%5D%5B%5D=&filters%5Bproject_ids%5D%5B%5D=&filters%5Bproject_group_ids%5D%5B%5D=&filters%5Bcohort_ids%5D%5B%5D=&filters%5Bhoh_only%5D=0&filters%5Bsub_population%5D=clients&filters%5Braces%5D%5B%5D=&filters%5Bage_ranges%5D%5B%5D=&filters%5Bgenders%5D%5B%5D=&filters%5Bveteran_statuses%5D%5B%5D=&filters%5Btimes_homeless_in_last_three_years%5D%5B%5D=&filters%5Bdisabilities%5D%5B%5D=&filters%5Bindefinite_disabilities%5D%5B%5D=&filters%5Bdv_status%5D%5B%5D=&filters%5Bchronic_status%5D=0&commit=Save+%26+Update

**Comment by ahogg77** [comment]
I closed the superset report.

**Pull request merged**
