### PR TITLE
Return Apollo errors in non-dev environments too

### PR DESCRIPTION
**Pull request by gigxz**
The message and backtrace will only be shown to the user in Dev, but I think we should always send them so they get to Sentry.

### CODE REVIEW

**Review by eanders — APPROVED** [review]
Looks fine to me.  I'll defer to @ttoomey

**Comment by gigxz** [comment]
Actually I changed my mind about this.. No need to send personal data back (in the `message`) since that should already be captured by the sentry backend. Moving convo to slack

**Comment by gigxz** [comment]
Ok, updated. I think this is what we want. I'm not sure if there are other unintended consequences of catching the exceptions, though.

**Review by ttoomey — APPROVED** [review]
Looks good!

**Pull request merged**
