### PR TITLE
Double the web cpu request, reduce deploy cpu, and increase DJ by 50%.

### PR DESCRIPTION
**Pull request by yakloinsteak**
## Description

This lets us configure CPU requests (shares) for ECS services. I'll change the secrets yaml after this is merged to lock in the values for QA, but we need this merged and deployed everywhere before we can start setting the values for all the other environments.

## Testing and Docs

With this PR, we'll be able to add sections like this to the secrets yaml. I'll test QA with and without this and make sure it works as expected.
```
  :cpu_shares:
    :workoff: 256
    :cron: 256
    :web: 1024
    :deploy: 128
    :dj: 384
```

## Type of change
- [x] reliability improvement

## checklist before requesting review
- [x] I have performed a self-review of my code
- [x] I have run the code that is being changed under ideal conditions, and it doesn't fail
- [x] My code includes comments and/or descriptive variable names to help other engineers understand the intent (or not applicable)
- [x] My code follows the style guidelines of this project (rubocop)
- [x] I have updated the documentation (or not applicable)
- [x] If it's not obvious how to test this change, I have provided testing instructions in this PR or the related issue

### CODE REVIEW

**Review by schwartzkylej — APPROVED** [review]
Looks good. Lets review once deployed to an environment. Thanks.

**Comment by eanders** [comment]
@yakloinsteak stupid question, we have similar functionality for memory usage that uses dynamodb (I think) should we port that into this setup, or maybe use that setup for this?  It feels like we're wiggling 2 very similar nobs but choosing two very dissimilar approaches.

**Review by eanders — APPROVED** [review]
Looks good, but I'm not 100% sure on the yaml storage for the source of truth.

**Comment by yakloinsteak** [comment]
I see the cpu as not being dynamically changing, while the RAM we try to adjust automatically. We can talk tomorrow about it.

**Comment by yakloinsteak** [comment]
I'm going to merge this and proceed in the interests of saving time. dynamodb won't get these values encoded in git (in terraform) and it's going to be very hard to nail down the right values dynamically anyway given how ECS works and how this parameter serves multiple purposes (reserving minimum CPU _and_ specifying how to divide up capacity when there's contention). We want the same values for all installations initially anyway to test our theory about this being the problem with occasional timeouts.

**Pull request merged**
