### PR TITLE
185000126 external referral authentication

### PR DESCRIPTION
**Pull request by ttoomey**
[185000126](https://www.pivotaltracker.com/story/show/185000126)

* add LINK spec against live auth
* fix up existing MCI spec
* extract generic oauth client spec from MCI, add stubs, include in main test-suite
* improve error handling in oauth client

### CODE REVIEW

**Review by gigxz — APPROVED** [review]
Thanks!

**Comment by eanders** [comment]
@ttoomey was there a specific reason this was merged into `stable` instead of `release-72`?
We don't generally do that except for hot-fixes.

Looks like this was mostly tests and some fixes, so maybe it's ok.

**Comment by ttoomey** [comment]
@eanders nope, my mistake. Looks like we merged r71 morning and this happened to my PR.
> Base automatically changed from release-71 to stable

I didn't catch this before I merged. Something I'll keep in mind in for the future. Apologies for the trouble

**Comment by eanders** [comment]
No worries.  I'm guessing this is safe to merge given the size.  We'll test.

**Comment by gigxz** [comment]
Whoops sorry I didn't catch that either.

**Pull request merged**
