### PR TITLE
Report filtration

### PR DESCRIPTION
**Pull request by jgoley**
@eanders This establishes the new structure and filtration of the reports table.
In adding the filtration of this list, I made updates to the roles/permissions filtration. Now if categories are selected then the user searches by keyword, it filters within those categories.

#### Todos:
- [x] Replace mock _recently viewed_ report category and reports with real data
- [x] Add category tags to recently viewed report list items
- [x] Search should search description as well
- [x] Style updates to items (color of description text)
- [x] Design alternative for category selection
- [x] Implement category selection
- [x] Fix issue when there is a search term and categories are toggled on (all of the reports of the category are added then they are searched — I guess we can search all the reports instead of scoping the text search to the reports of the active categories)
- [x] Breadcrumbs should be somewhat useful (roughly as useful as they are now)
- [x] Allow selection of only 1 category (if all categories is not selected)
- [x] Fix issues with search looking in hidden categories

### CODE REVIEW

**Comment by jgoley** [comment]
@eanders How does [something like this](https://xd.adobe.com/view/3aeecfb1-862b-4da9-9166-a25d1467a301-6fbd/) look for the category filtration? (there are a few clickable areas)
The treatment of the items (the eyeball icon and such can change).

**Comment by eanders** [comment]
I say yes!  Especially if we can figure out how to make the JS slightly smart so if you click off of All Reports it gets unchecked, and you can select multiple categories.  I'm not opposed to the stimulus idea, but I'm not sure we need to make round-trips to the DB or server for this.

**Comment by jgoley** [comment]
@eanders Just pushed some updates that roughly implement the above design (without the checkmarks for now will add those ASAP).
I haven't added functionality to hide the category titles when the user searches by term and then all the items are hidden.

**Comment by jgoley** [comment]
@eanders Just pushed a few updates which take care of the remaining todos.
When the user navigates back from a report show page, the report's group will be selected.
I also, within the recently viewed reports section, switched the name within the badges to the report's group name.

**Comment by jgoley** [comment]
Oh! I suppose at some point we should could refactor the other instances of the filtered list to use the new stimulus controller logic.

**Comment by eanders** [comment]
@jgoley , this is looking great! Thanks.  I'm finding one interaction odd.  The ability to choose more than one category at a time is confusing if you add categories that are below the previously selected items because the change occurs "below the fold." Can we adjust so that you can only have one category chosen at a time?  Then "All Reports" would list all of the categories, but choosing anything else would replace the visible set instead of appending/prepending.

It also behaves oddly if you have a search and then click headings because it doesn't show section with no report matches but the search box says "Number of reports found: 4."  Try searching for RRH, then clicking Audit, CAS, Data Quality.  Audit and Data Quality don't have any affect, CAS shows up with a result.  This is a very minor bug, but might be worth addressing.  Thee possibilities I can think of:

1. Clear the search when you click on a category (this isn't really ideal as searching might be frustrating if it keeps forgetting your search)
2. Show the header that you clicked on with "no matching reports" if there's a search but no matching reports
3. Typing in the search box always bumps you to the "All Reports" option so you can see anything that matches

Maybe you can give me a tour of the stimulus work next week?  Overall this looks great.  Thanks!

**Comment by eanders** [comment]
@jgoley this looks amazing to me.  Thanks!

**Pull request merged**
