### PR TITLE
Remove length restriction from SHE project_name

### PR DESCRIPTION
**Pull request by eanders**
## _Merging this PR_
- use the squash-merge strategy for PRs targeting a release-X branch

## Description
[//]: # (Summarize changes and include links related issue. List any new dependencies)
* Removes the length discrepancy between `Project.ProjectName` and `service_history_enrollments.project_name`

## Type of change
[//]: # (e.g., Bug fix, New feature, Code clean-up, Dependency update)
* Bug fix

## Checklist before requesting review
[//]: # (Remove any items that are not applicable)
- [x] I have performed a self-review of my code
- [x] I have run the code that is being changed under ideal conditions, and it doesn't fail
- [ ] I have updated the documentation (or not applicable)
- [ ] I have added spec tests (or not applicable)
- [ ] I have provided testing instructions in this PR or the related issue (or not applicable)

[//]: # NOTE: system tests may fail if there is no branch on the hmis-frontend that matches the Source  or Target branch of this PR. This is expected

### CODE REVIEW

**Comment by eanders** [comment]
@gigxz let me know if you think this should go in 143 (or feel free to retarget it.)

**Review by gigxz — APPROVED** [review]
Looks good, thanks! I think 143 would be acceptable since this bug is not impacting production, but 142 is fine with me too.

Is there a backstory for this view not being managed with `scenic`? It's nice to have the view history available at `db/views`.

**Comment by eanders** [comment]
We could move the view to scenic.  I think we created it before we had scenic.

**Comment by gigxz** [comment]
Alright- just wondering- don't think that should block merge!

**Pull request merged**
