### PR TITLE
Rails microversion bump to find deprecations

### PR DESCRIPTION
**Pull request by yakloinsteak**

### CODE REVIEW

**Comment by yakloinsteak** [comment]
@eanders What's the process you'd like for these PRs related to the rails upgrade? Should it be against a release branch? Want me to test on QA a little first?

**Comment by eanders** [comment]
@yakloinsteak if you can deploy to QA to confirm that it deploys and pages load, a PR against the release branch would be perfect.

**Comment by yakloinsteak** [comment]
@eanders QA deploys and boots with this.

**Review by eanders — APPROVED** [review]
Waiting on some manual testing to merge.

**Pull request merged**
