### PR TITLE
Add an Encoding detecting CSV reader and some test data

### PR DESCRIPTION
**Pull request by amichal**
We sometimes get CSV data in the wrong encoding (spec requires UTF-8). For many common case we can detect and recover. Add support to do that with `AutoEncodingCsv` which has a `AutoEncodingCsv.open` as a drop-in replacement subclass for `CSV.open` that will auto-detect common encodings if the `encoding` option is left blank. This also works for `.read` and other class methods. A quick scan of the codebase shows we typically use one of the methods that takes a filename to open. We can also patch the `IO` methods like `.new` as needed 

Uses magic bytes to choose between:
- UTF-8 + BOM (commonly generated by Excel
- UTF-16LE (also a common Excel export format)
- UTF-16BE (rarely seen but easy)

Failing a match for those common cases we check statistically via CharlockHolmes/ICU others and have test coverage for:
- UTF-8
- Windows 1252 - e.g. English Windows and very similar to/superseded by ISO-8851-1
- <del>macRoman - probably not seem much anymore but saving a XLSX as a "CSV" in Excel for Mac used to do this by default.</del> There is a test file but its similar enough that `CharlockHolmes` thinks its Windows-1252. A bigger file might work if we ever see one in the wild 🤷 

CharlockHolmes/ICU may detect other less common encodings as well but we are not seeing those in the wild.

- [x] Encoding guessing for common variations
### Potential Use-cases
- [x] Use everywhere in`drivers/hmis_csv_twenty_twenty/*`
- [x] `app/models/importers/*` Leave alone except `app/models/importers/hmis_auto_detect.rb` which looks up `available_importers`
- [x] `spec/*` and `*exporter*` Leave alone. Exporters must generate UTF-8 CSVs per spec
- [x] `drivers/claims_reporting/*` Leave it. We always get UTF8

### CODE REVIEW

**Comment by amichal** [comment]
@eanders This is a unit-tested component at the moment. If you point out some places we want it used I'll happily drop them in and tweak tests as needed.

**Comment by amichal** [comment]
Ugh... let me rebase before its ready for you. Got in an overcommit/git commit --amend fight

**Comment by eanders** [comment]
@amichal , this looks awesome and elegant.  Places we need to drop it in:
https://github.com/greenriver/hmis-warehouse/blob/c4d880a1992363139f22278248c1e7b374833b93/drivers/hmis_csv_twenty_twenty/app/models/hmis_csv_twenty_twenty/loader/loader.rb#L225
https://github.com/greenriver/hmis-warehouse/blob/c4d880a1992363139f22278248c1e7b374833b93/drivers/hmis_csv_twenty_twenty/app/models/hmis_csv_twenty_twenty/loader/loader.rb#L225
https://github.com/greenriver/hmis-warehouse/blob/c4d880a1992363139f22278248c1e7b374833b93/drivers/hmis_csv_twenty_twenty/app/models/hmis_csv_twenty_twenty.rb#L11
https://github.com/greenriver/hmis-warehouse/blob/c4d880a1992363139f22278248c1e7b374833b93/drivers/hmis_csv_twenty_twenty/app/models/hmis_csv_twenty_twenty/loader/export.rb#L17

**Comment by amichal** [comment]
@eanders Ready for you. I did the 2020 importer only and with minimal code changes to it, added a spec for coverage. I *might* have broken a special case we had in there for something that got detected as UTF32-BE which I don't recall why we had it. Seems nearly impossible to find such a CSV file in the wild so If you remind me I can add coverage back in for that but this is otherwise good to merge I think. I had a big check list of other CSV handling code that could use this but realized those are all separate steps/involved in other moving parts.

**Pull request merged**
