### PR TITLE
String IO security update

### PR DESCRIPTION
**Pull request by eanders**
[//]: # 'remove this if PR is for a release-* branch'
# _Please squash merge this PR_

## Description
* Upgrade to ruby 3.1.6
* Upgrade to alpine 3.20
* Security update for stringio gem

## Type of change
[//]: # 'remove options that are not relevant'
- [x] Dependency update

## Checklist before requesting review
- [ ] I have performed a self-review of my code
- [ ] I have run the code that is being changed under ideal conditions, and it doesn't fail
- [ ] My code includes comments and/or descriptive variable names to help other engineers understand the intent (or not applicable)
- [ ] My code follows the style guidelines of this project (rubocop)
- [ ] I have updated the documentation (or not applicable)
- [ ] If it's not obvious how to test this change, I have provided testing instructions in this PR or the related issue

### CODE REVIEW

**Review by ttoomey — COMMENTED** [review]
didn't we do this already here?
https://github.com/greenriver/hmis-warehouse/pull/4515

also I don't think we need stringio in the Gemfile

**Comment by eanders** [comment]
We did, but it seems to still be failing.  This was a different attempt to fix it, which seems to also be failing.

**Review by ttoomey — APPROVED** [review]

**Comment by ttoomey** [comment]
@eanders built this locally, seems to work as expected

**Comment by eanders** [comment]
Oh, awesome, thank you!  I'll give it a run locally.

**Comment by eanders** [comment]
Had to run 
```
rvm reinstall 3.1.6 --with-openssl-dir=$(brew --prefix openssl@3) --enable-yjit --reconfigure
```
To get ruby 3.1.6 to install on Mac OS 14.5 (Sonoma) on an M1

**Comment by eanders** [comment]
Thanks @ttoomey! Seems to work well.

**Pull request merged**
